In [ ]:
print("hello world")

# 这是第一个文档

In [14]:
import numpy as np
arr = np.random.randint(1,10)
print(arr) ## 随机生成一个数1到10 之间

8


In [20]:
import numpy as np 
arr = [1,5,4,6,7,8]
arr = np.array(arr,dtype = np.double)
for i in range(arr.size):
    print(i)
    print(arr[i])

1.0
5.0
4.0
6.0
7.0
8.0


In [2]:
import pickle
import numpy as np

your_data = np.ones((4,5),np.uint8)
# your_data = [np.ones((4,5), np.uint8), np.ones((8,9), np.int64)]  什么结构都可以
# wb 以二进制写入

data_output = open('111.pkl','wb')
pickle.dump(your_data,data_output)
data_output.close()

# rb 以二进制读取
data_input = open('111.pkl','rb')
read_data = pickle.load(data_input)
print(read_data)
data_input.close()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
import librosa
import matplotlib as mpl
import matplotlib.pyplot as plt
y,sr = librosa.load('/home/lrs/dengfeng.p/break_feature/f001001_01.wav',sr = 16000,mono = False)
print(y.shape,sr) 
x = librosa.feature.rms(y=y[0],hop_length=160)
plt.plot(x[0])
plt.show()
# print(x)

/home/lrs/miniconda3/envs/pytorch/lib/python3.8/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)


FileNotFoundError: [Errno 2] No such file or directory: '/home/lrs/dengfeng.p/break_feature/f001001_01.wav'